version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TestPostnordTransport"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3"
s3_prefix = "TestPostnordTransport"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ContextId=\"550\" ClientId=\"ThetisClientId\" ClientSecret=\"ThetisClientSecret\" ApiKey=\"ccffdc7f-1be2-46f8-85e5-81106aa284eb\""
